disabled_rules:
    - todo
    - discouraged_direct_init
    - cyclomatic_complexity

type_name:
    max_length:
      warning: 50
      error: 60

identifier_name:
    excluded:
      - up
      - id
      - db
